<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <RootNamespace>ShopWebApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="dbup-postgresql" Version="6.0.0-beta.44" />
        <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShopWebApp.Application\ShopWebApp.Application.csproj" />
      <ProjectReference Include="..\ShopWebApp.Domain\ShopWebApp.Domain.csproj" />
      <ProjectReference Include="..\ShopWebApp.Infrastructure\ShopWebApp.Infrastructure.csproj" />
    </ItemGroup>

</Project>
